### ISSUE TITLE
Extra double-quotes in AT+CWJAP

### ISSUE THREAD

**Issue by pradeeka7** [KalbeAbbas/pxt-CW01#1]
Hi Kalbe,

![image](https://user-images.githubusercontent.com/36432168/65650181-5bccb700-e027-11e9-8a65-48b029326809.png)

![image](https://user-images.githubusercontent.com/36432168/65650286-d564a500-e027-11e9-8b72-a28f4008ea7b.png)

The 'Connect to WiFi' block doesn't provide any response (actually it doesn't work) because of the extra 'double quotes' found in the string. Could you please double-check and update the code ASAP? 

Thanks,
Pradeeka

**Comment by KalbeAbbas** [comment]
Hi Pradeeka,

Adding extra double quotes to the SSID and PSK is required by AT-instruction set as mentioned in their [doc](https://www.espressif.com/sites/default/files/documentation/4a-esp8266_at_instruction_set_en.pdf):

![at-joinWifi](https://user-images.githubusercontent.com/49709412/65663501-6a7b9400-e050-11e9-9cae-c3aa8bf522e0.png)

Please make sure you have flashed XinaBox version of AT-instruction set to CW01(ESP8266), [link](https://github.com/xinabox/XinaBoxUploader) . And that you are using correct XinaBox microbit bridge ( IM01). If not using IM01, connect pin1 of microbit to RX of esp8266 and pin0 of microbit to TX of esp8266.

Please also send serial monitor log of ESP8266 for better understanding, you can use Arduino IDE for this.

Thanks,
KalbeAbbas

**Comment by pradeeka7** [comment]
Hi Kalbe,

Thanks for the clarifications. 

I don't have an IM01 bridge yet. I tested with the BM11 bridge.
My IM01 is on the way. I will test the code again once I received it.

Thanks,
Pradeeka
