### ISSUE TITLE
MQTT server port

### ISSUE THREAD

**Issue by pradeeka7** [KalbeAbbas/pxt-CW01#2]
Hi Kalbe,

It seems you use port 80 instead of 1883 for MQTT. Is that correct?

Thanks,
Pradeeka

**Comment by KalbeAbbas** [comment]
Hi Pradeeka,

No, the library actually uses HTTP API to connect many IoT platfotms. We are not using MQTT for this, so using port 80 for HTTP.

Let me know if the library works for you.

Thanks
KalbeAbbas

**Comment by pradeeka7** [comment]
Hi Kalbe,

We have written the chapter for Okdo 'MQTT.' Now we have to change that for HTTP. First I want to discuss with Philip about this matter. I think he also expects MQTT. Let's see. I'll update you shortly.

Thanks,
Pradeeka

**Comment by pradeeka7** [comment]
Hi Kalbe,

We can use HTTP for our book. So, I will close this issue. Thanks.
